version: "3.9"

services:
  demo-flask-app:
    container_name: demo-flask-app
    build:
      context: .
    ports:
    - "5000:5000"
    networks:
      - all-plugins-nginx-plugins_app_network

networks:
  all-plugins-nginx-proxy_app_network:
    external: true
    driver: bridge